### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by blah238** [ziyasal/atom-open-conemu-here#1]
Is it possible to configure the path to the executable? Specifically I would like to use [Cmder](http://gooseberrycreative.com/cmder/) which is a Conemu wrapper.

**Comment by blah238** [comment]
Looks like it is configurable through `.atom/config.cson`: 

``` cson
  "open-conemu-here":
    win32App: "Cmder.exe"
    win32Args: ""
```

Unfortunately the `/Dir` switch is not supported in Cmder, where the equivalent is called `/START`.

**Comment by blah238** [comment]
PR https://github.com/ziyasal/atom-open-conemu-here/pull/3 makes this more easily configurable through the Settings panel.

**Comment by bugthesystem** [comment]
:+1:  Thanks.
